### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by NCBarrett** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#10]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#4

**In which task and step of the codelab can this issue be found?**
Add images to your Android app, Step 5: solution code

**Describe the problem**
As directed, I opened the project folder and waited for Android Studio to open the project. However, the Run button wasn't available to build and run the app. I don't currently have the know-how to solve this problem.

**Steps to reproduce?**
See "Describe the problem."
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_ ?

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Android Studio screenshot](https://user-images.githubusercontent.com/80253863/110308172-a7bdb280-7fb4-11eb-9aa7-ad9c1300201d.jpg)

**Comment by ashnohe** [comment]
Thank you @NCBarrett for raising this issue. Opening "Happy Birthday" instead of "android-basics-kotlin-birthday-card-with-image-app-solution-master" will resolve this issue.

Marking this as a documentation issue. Under "Open the project in Android Studio" step 4 should read "Double-click on the _Happy Birthday_ project folder" so developers do not open the root folder, "android-basics-kotlin-birthday-card-with-image-app-solution-master".

**Comment by ashnohe** [comment]
#26 has a good explanation
